name: Open homework 8

on: workflow_dispatch

jobs: 
  homework_removal:
    name: Open homework 8
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm ci
      - run: node ./scripts/homework-8.js
